### ISSUE TITLE
Gnome lock screen notification from owncloud

### ISSUE THREAD

**Issue by smichel17** [nextcloud/client_theming#86]
Fedora 25, gnome 3.22.3

Steps to reproduce:

- Run the nextcloud client
- Connect to a server
- Update a file on the server, not through the client, so that the client shows a `file was updated` notification
- Lock the screen

Expected result: `nextcloud: 1 missed notification`
Actual result: `owncloud: 1 missed notification`

**Comment by hanzei** [comment]
Same on gnome 3.20.4

**Comment by juliusknorr** [comment]
I created a PR to fix this issue here: https://github.com/owncloud/client/pull/5677

**Comment by rugk** [comment]
https://github.com/owncloud/client/pull/5677 was merged. Thus this issue can be closed IMHO.

**Comment by enoch85** [comment]
This issue has been inactive for some time now. 

Is this issue related to the ownCloud client, (thus not an **theming** isssue) please close it and report the issue [here](https://github.com/owncloud/client) instead.
Is this issue related to this repo but solved, please close it and if possible let us know what solved the issue.
Is this issue still not solved, please let us know as well.

If I don't hear anything from the one who created this issue within 2 weeks, I will close the issue.

**Comment by smichel17** [comment]
The issue is that the notification calls the application `owncloud`, not `nextcloud`. On the surface, that would *seem* like a theming issue to me (string that needs to be changed somewhere), but it looks like it is resolved 4 days ago by @juliushaertl in https://github.com/owncloud/client/pull/5677. That leaves me uncertain whether it should be considered a theming issue or not.

I am running the most recent version of the nextcloud client available in the Fedora 25 repos, v2.2.4, which does not have the fix yet. If you decide not to close this issue now, I'll do it when a fix makes it to my computer.

**Comment by enoch85** [comment]
OK, let's leave it open for now. Please remember to close once it's fixed. Thanks! :)

**Comment by enoch85** [comment]
Merged.

**Comment by elpraga** [comment]
I still get the name __ownCloud__ on the lock screen after the last update if the client. 

Could you check @enoch85 if the string has been changed accordingly?

**Comment by enoch85** [comment]
@elpraga This is in beta and hasn't reached stable yet.

**Comment by elpraga** [comment]
Ok. Thanks for clarifying!
